import nodemailer from 'nodemailer';
import { config } from '../config';

/**
 * Interface for the insight report data
 */
export interface InsightReport {
  insights: string[];
  warning: string;
  recommendation: string;
}

/**
 * Configure the email transporter
 */
const transporter = nodemailer.createTransport({
  host: process.env.EMAIL_HOST || 'smtp.gmail.com',
  port: parseInt(process.env.EMAIL_PORT || '587'),
  secure: process.env.EMAIL_SECURE === 'true',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

/**
 * Send weekly report email to user
 */
export const sendWeeklyReport = async (userEmail: string, insightData: InsightReport) => {
  if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
    console.error('Email credentials are not configured');
    return;
  }

  const insightList = insightData.insights.map((insight) => `<li>${insight}</li>`).join('');

  const mailOptions = {
    from: `"AI Personal Finance" <${process.env.EMAIL_USER}>`,
    to: userEmail,
    subject: 'Your Weekly Financial Report',
    html: `
      <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;">
        <div style="background-color: #4A90E2; color: white; padding: 20px; text-align: center;">
          <h1 style="margin: 0;">Weekly Financial Report</h1>
        </div>
        <div style="padding: 20px;">
          <h2 style="color: #4A90E2; border-bottom: 2px solid #4A90E2; padding-bottom: 5px;">Insights</h2>
          <ul>
            ${insightList}
          </ul>

          <h2 style="color: #D0021B; border-bottom: 2px solid #D0021B; padding-bottom: 5px;">Warning</h2>
          <p style="background-color: #FFF5F5; border-left: 5px solid #D0021B; padding: 10px;">
            ${insightData.warning}
          </p>

          <h2 style="color: #417505; border-bottom: 2px solid #417505; padding-bottom: 5px;">Recommendation</h2>
          <p style="background-color: #F8FFF0; border-left: 5px solid #417505; padding: 10px;">
            ${insightData.recommendation}
          </p>
        </div>
        <div style="background-color: #F9F9F9; padding: 10px; text-align: center; font-size: 12px; color: #777;">
          <p>This is an automated report generated by your AI Personal Finance Autopilot.</p>
        </div>
      </div>
    `,
  };

  try {
    await transporter.sendMail(mailOptions);
    console.log(`Weekly report sent to ${userEmail}`);
  } catch (error) {
    console.error(`Error sending email to ${userEmail}:`, error);
  }
};
